services:
  db:
    image: postgres:15-alpine
    container_name: vetclinic-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mat1pop4315
      POSTGRES_DB: mypoject
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: vetclinic-backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: mat1pop4315
      DB_NAME: mypoject
    volumes:
      - ./frontend:/app/static
    depends_on:
      - db
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: vetclinic-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@vet.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
